#include <iostream>
#include "SOutil.h"
#include "rlutil.h"
using namespace rlutil;

#include "dibujo.h"
using namespace std;
#include <windows.h>


void cuadros(){

    setColor(LIGHTMAGENTA);
    gotoxy(35, 4);
    cout << " ___________________________________________________" <<endl;
    gotoxy(35, 5);
    cout << "| _________________________________________________ |" <<endl;
    gotoxy(35, 6);
    cout << "||" <<endl;
    gotoxy (86, 6);
    cout << "||" <<endl;
    gotoxy(35, 7);
    cout << "||" <<endl;
    gotoxy(86, 7);
    cout << "||" <<endl;
    gotoxy(35, 8);
    cout << "||_________________________________________________||";
    gotoxy(35, 9);
    cout << "||";
    gotoxy (86, 9);
    cout << "||"<<endl;
    gotoxy(35, 10);
    cout << "||";
    gotoxy (86, 10);
    cout << "||"<<endl;
    gotoxy(35, 11);
    cout << "||";
    gotoxy (86, 11);
    cout << "||"<<endl;
    gotoxy(35, 12);
    cout << "||";
    gotoxy (86, 12);
    cout << "||"<<endl;
    gotoxy(35, 13);
    cout << "||";
    gotoxy (86, 13);
    cout << "||"<<endl;
    gotoxy(35, 14);
    cout << "||";
    gotoxy (86, 14);
    cout << "||"<<endl;
    gotoxy(35, 15);
    cout << "||";
    gotoxy (86, 15);
    cout << "||"<<endl;
    gotoxy(35, 16);
    cout << "||";
    gotoxy (86, 16);
    cout << "||"<<endl;
    gotoxy(35, 17);
    cout << "||";
    gotoxy (86, 17);
    cout << "||"<<endl;
    gotoxy(35, 18);
    cout << "||";
    gotoxy (86, 18);
    cout << "||"<<endl;
    gotoxy(35, 19);
    cout << "||";
    gotoxy (86, 19);
    cout << "||"<<endl;
    gotoxy(35, 20);
    cout << "||";
    gotoxy (86, 20);
    cout << "||"<<endl;
    gotoxy(35, 21);
    cout << "||";
    gotoxy (86, 21);
    cout << "||"<<endl;
    gotoxy(35, 22);
    cout << "||";
    gotoxy (86, 22);
    cout << "||"<<endl;
    gotoxy(35, 23);
    cout << "||";
    gotoxy (86, 23);
    cout << "||"<<endl;
    gotoxy(35, 24);
    cout << "||";
    gotoxy (86, 24);
    cout << "||"<<endl;
    gotoxy(35, 25);
    cout << "||_________________________________________________||" <<endl;
    gotoxy(35, 26);
    cout << "|___________________________________________________|" <<endl;

    setColor(WHITE);
}

void cuadrosLista2(){

    setColor(LIGHTCYAN);
    gotoxy(3, 2);
    cout << " ________________________________________________________________________________________________________" <<endl;
    gotoxy(3, 3);
    cout << "|________________________________________________________________________________________________________|" <<endl;
    gotoxy(3, 4);
    cout << "|" <<endl;
    gotoxy (107, 4);
    cout << " |" <<endl;
    gotoxy(3, 5);
    cout << "|" <<endl;
    gotoxy(107, 5);
    cout << " |" <<endl;
    gotoxy(3, 6);
    cout << "|________________________________________________________________________________________________________|";
    setColor(WHITE);
}

void cuadrosLista(){

    setColor(LIGHTCYAN);
    gotoxy(3, 2);
    cout << " ________________________________________________________________________________________________________" <<endl;
    gotoxy(3, 3);
    cout << "|________________________________________________________________________________________________________|" <<endl;
    gotoxy(3, 4);
    cout << "|" <<endl;
    gotoxy (107, 4);
    cout << " |" <<endl;
    gotoxy(3, 5);
    cout << "|" <<endl;
    gotoxy(107, 5);
    cout << " |" <<endl;
    gotoxy(3, 6);
    cout << "|________________________________________________________________________________________________________|";
    gotoxy(3, 7);
    cout << "|";
    gotoxy (107, 7);
    cout << " |"<<endl;
    gotoxy(3, 8);
    cout << "|";
    gotoxy (107, 8);
    cout << " |"<<endl;
    gotoxy(3, 9);
    cout << "|";
    gotoxy (107, 9);
    cout << " |"<<endl;
    gotoxy(3, 10);
    cout << "|";
    gotoxy (107, 10);
    cout << " |"<<endl;
    gotoxy(3, 11);
    cout << "|";
    gotoxy (107, 11);
    cout << " |"<<endl;
    gotoxy(3, 12);
    cout << "|";
    gotoxy (107, 12);
    cout << " |"<<endl;
    gotoxy(3, 13);
    cout << "|";
    gotoxy (107, 13);
    cout << " |"<<endl;
    gotoxy(3, 14);
    cout << "|";
    gotoxy (107, 14);
    cout << " |"<<endl;
    gotoxy(3, 15);
    cout << "|";
    gotoxy (107, 15);
    cout << " |"<<endl;
    gotoxy(3, 16);
    cout << "|";
    gotoxy (107, 16);
    cout << " |"<<endl;
    gotoxy(3, 17);
    cout << "|";
    gotoxy (107, 17);
    cout << " |"<<endl;
    gotoxy(3, 18);
    cout << "|";
    gotoxy (107, 18);
    cout << " |"<<endl;
    gotoxy(3, 19);
    cout << "|";
    gotoxy (107, 19);
    cout << " |"<<endl;
    gotoxy(3, 20);
    cout << "|";
    gotoxy (107, 20);
    cout << " |"<<endl;
    gotoxy(3, 21);
    cout << "|";
    gotoxy (107, 21);
    cout << " |"<<endl;
    gotoxy(3, 22);
    cout << "|";
    gotoxy (107, 22);
    cout << " |"<<endl;
    gotoxy(3, 23);
    cout << "|";
    gotoxy (107, 23);
    cout << " |"<<endl;
    gotoxy(3, 24);
    cout << "|";
    gotoxy (107, 24);
    cout << " |"<<endl;
    gotoxy(3, 25);
    cout << "|";
    gotoxy (107, 25);
    cout << " |"<<endl;
    gotoxy(3, 26);
    cout << "|";
    gotoxy (107, 26);
    cout << " |"<<endl;
    //gotoxy(3, 27);
    //cout << "|________________________________________________________________________________________________________|" <<endl;
    //gotoxy(3, 28);
    //cout << "|________________________________________________________________________________________________________|" <<endl;

    setColor(WHITE);
}


void cuadros2(){

    setColor(LIGHTCYAN);
    gotoxy(35, 4);
    cout << " ___________________________________________________" <<endl;
    gotoxy(35, 5);
    cout << "|___________________________________________________|" <<endl;
    gotoxy(35, 6);
    cout << "|" <<endl;
    gotoxy (86, 6);
    cout << " |" <<endl;
    gotoxy(35, 7);
    cout << "|" <<endl;
    gotoxy(86, 7);
    cout << " |" <<endl;
    gotoxy(35, 8);
    cout << "|___________________________________________________|";
    gotoxy(35, 9);
    cout << "|";
    gotoxy (86, 9);
    cout << " |"<<endl;
    gotoxy(35, 10);
    cout << "|";
    gotoxy (86, 10);
    cout << " |"<<endl;
    gotoxy(35, 11);
    cout << "|";
    gotoxy (86, 11);
    cout << " |"<<endl;
    gotoxy(35, 12);
    cout << "|";
    gotoxy (86, 12);
    cout << " |"<<endl;
    gotoxy(35, 13);
    cout << "|";
    gotoxy (86, 13);
    cout << " |"<<endl;
    gotoxy(35, 14);
    cout << "|";
    gotoxy (86, 14);
    cout << " |"<<endl;
    gotoxy(35, 15);
    cout << "|";
    gotoxy (86, 15);
    cout << " |"<<endl;
    gotoxy(35, 16);
    cout << "|";
    gotoxy (86, 16);
    cout << " |"<<endl;
    gotoxy(35, 17);
    cout << "|";
    gotoxy (86, 17);
    cout << " |"<<endl;
    gotoxy(35, 18);
    cout << "|";
    gotoxy (86, 18);
    cout << " |"<<endl;
    gotoxy(35, 19);
    cout << "|";
    gotoxy (86, 19);
    cout << " |"<<endl;
    gotoxy(35, 20);
    cout << "|";
    gotoxy (86, 20);
    cout << " |"<<endl;
    gotoxy(35, 21);
    cout << "|";
    gotoxy (86, 21);
    cout << " |"<<endl;
    gotoxy(35, 22);
    cout << "|";
    gotoxy (86, 22);
    cout << " |"<<endl;
    gotoxy(35, 23);
    cout << "|";
    gotoxy (86, 23);
    cout << " |"<<endl;
    gotoxy(35, 24);
    cout << "|";
    gotoxy (86, 24);
    cout << " |"<<endl;
    gotoxy(35, 25);
    cout << "|___________________________________________________|" <<endl;
    gotoxy(35, 26);
    cout << "|___________________________________________________|" <<endl;

    setColor(WHITE);
}

void imagen_bienvenida(){
    //int sleep100=100;
    setColor(LIGHTMAGENTA);
    gotoxy(3,27);
    cout << "By Lau Mendoza";
    setColor(LIGHTCYAN);
    gotoxy(3,24);
    cout << "_____________   _____________   _____________   _____________   _____________   _____________   " <<endl;
    gotoxy(3,25);
    cout << "_________   _____________   _____________   _____________   _____________   _____________   ____" <<endl;
    setColor(LIGHTMAGENTA);
    for (int i=0; i<25; i++){
        if (i%2==0) setColor(LIGHTMAGENTA);
        else setColor(LIGHTCYAN);
        gotoxy(3+i, 5);
        cout << "       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 6);
        cout << "      OO        OO        OO        OO       OO" <<endl;
        gotoxy(5+i, 7);
        cout << "       OOO     OOOO       OOOO      OOOO       OO" <<endl;
        gotoxy(5+i, 8);
        cout << "        OOOOOOOO   OOOOOOOO  OOOOOOOO   OOOOOOOO" <<endl;
        gotoxy(5+i, 9);
        cout << "        OOO                                   OO" <<endl;
        gotoxy(5+i, 10);
        cout << "        OOO    OOOOOOOOOOOOOOOOOOOOOOOOO     OOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 11);
        cout << "        OOO   OOO                      OO    OO           OOO" <<endl;
        gotoxy(5+i, 12);
        cout << "        OOO   OOO      FOOD TRUCK      OO    OO             OO" <<endl;
        gotoxy(5+i, 13);
        cout << "        OOO   OOO         APP          OO    OO              OOO" <<endl;
        gotoxy(5+i, 14);
        cout << "        OOO   OOO                      OO    OOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 15);
        cout << "        OOO   OOOOOOOOOOOOOOOOOOOOOOOOOOOO   OO                     OOOO" <<endl;
        gotoxy(5+i, 16);
        cout << "        OOO                                  OO                      OOOO" <<endl;
        gotoxy(5+i, 17);
        cout << "        OOO         ooooo                    OO              ooooo       OO" <<endl;
        gotoxy(5+i, 18);
        cout << "        OO      ooo      ooo                 OO           ooo     ooo   OO" <<endl;
        gotoxy(5+i, 19);
        cout << "        OOOOOOoooo OOOOOOO ooooOOOOOOOOOOOOOOOOOOOOOOOOoooo OOOOOO oooo" <<endl;
        gotoxy(5+i, 20);
        cout << "               oo ooo   ooo oo                           oo ooo  ooo oo" <<endl;
        gotoxy(5+i, 21);
        cout << "               ooo ooooo ooo                             ooo oooooo oo" <<endl;
        gotoxy(5+i, 22);
        cout << "                 ooo    ooo                               ooo     ooo" <<endl;
        gotoxy(5+i, 23);
        cout << "                     ooo                                      ooo" <<endl <<endl <<endl;

    }
    getch();
}

void imagen_eliminando(){
    setColor(LIGHTCYAN);
    gotoxy(3,24);
    cout << "_____________   _____________   _____________   _____________   _____________   _____________   " <<endl;
    gotoxy(3,25);
    cout << "_________   _____________   _____________   _____________   _____________   _____________   ____" <<endl;
    setColor(LIGHTMAGENTA);
    for (int i=0; i<25; i++){
        gotoxy(3+i, 5);
        cout << "       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 6);
        cout << "      OO        OO        OO        OO       OO" <<endl;
        gotoxy(5+i, 7);
        cout << "       OOO     OOOO       OOOO      OOOO       OO" <<endl;
        gotoxy(5+i, 8);
        cout << "        OOOOOOOO   OOOOOOOO  OOOOOOOO   OOOOOOOO" <<endl;
        gotoxy(5+i, 9);
        cout << "        OOO                                   OO" <<endl;
        gotoxy(5+i, 10);
        cout << "        OOO    OOOOOOOOOOOOOOOOOOOOOOOOO     OOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 11);
        cout << "        OOO   OOO                      OO    OO           OOO" <<endl;
        gotoxy(5+i, 12);
        cout << "        OOO   OOO      ELIMINANDO      OO    OO             OO" <<endl;
        gotoxy(5+i, 13);
        cout << "        OOO   OOO                      OO    OO              OOO" <<endl;
        gotoxy(5+i, 14);
        cout << "        OOO   OOO                      OO    OOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 15);
        cout << "        OOO   OOOOOOOOOOOOOOOOOOOOOOOOOOOO    OO                    OOOO" <<endl;
        gotoxy(5+i, 16);
        cout << "        OOO                                   OO                     OOOO" <<endl;
        gotoxy(5+i, 17);
        cout << "        OOO         ooooo                     OO             ooooo       OO" <<endl;
        gotoxy(5+i, 18);
        cout << "        OO      ooo      ooo                  OO          ooo     ooo   OO" <<endl;
        gotoxy(5+i, 19);
        cout << "        OOOOOOoooo OOOOOOO ooooOOOOOOOOOOOOOOOOOOOOOOOOoooo OOOOOO oooo" <<endl;
        gotoxy(5+i, 20);
        cout << "               oo ooo   ooo oo                           oo ooo  ooo oo" <<endl;
        gotoxy(5+i, 21);
        cout << "               ooo ooooo ooo                             ooo oooooo oo" <<endl;
        gotoxy(5+i, 22);
        cout << "                 ooo    ooo                               ooo     ooo" <<endl;
        gotoxy(5+i, 23);
        cout << "                     ooo                                      ooo" <<endl <<endl <<endl;

    }
    setColor(WHITE);
}

void imagen_backup(){
    setColor(LIGHTCYAN);
    gotoxy(3,24);
    cout << "_____________   _____________   _____________   _____________   _____________   _____________   " <<endl;
    gotoxy(3,25);
    cout << "_________   _____________   _____________   _____________   _____________   _____________   ____" <<endl;
    setColor(LIGHTMAGENTA);
    for (int i=0; i<25; i++){
        gotoxy(3+i, 5);
        cout << "       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 6);
        cout << "      OO        OO        OO        OO       OO" <<endl;
        gotoxy(5+i, 7);
        cout << "       OOO     OOOO       OOOO      OOOO       OO" <<endl;
        gotoxy(5+i, 8);
        cout << "        OOOOOOOO   OOOOOOOO  OOOOOOOO   OOOOOOOO" <<endl;
        gotoxy(5+i, 9);
        cout << "        OOO                                   OO" <<endl;
        gotoxy(5+i, 10);
        cout << "        OOO    OOOOOOOOOOOOOOOOOOOOOOOOO     OOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 11);
        cout << "        OOO   OOO                      OO    OO           OOO" <<endl;
        gotoxy(5+i, 12);
        cout << "        OOO   OOO      REALIZANDO      OO    OO             OO" <<endl;
        gotoxy(5+i, 13);
        cout << "        OOO   OOO       BACK UP        OO    OO              OOO" <<endl;
        gotoxy(5+i, 14);
        cout << "        OOO   OOO                      OO    OOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 15);
        cout << "        OOO   OOOOOOOOOOOOOOOOOOOOOOOOOOOO    OO                    OOOO" <<endl;
        gotoxy(5+i, 16);
        cout << "        OOO                                   OO                     OOOO" <<endl;
        gotoxy(5+i, 17);
        cout << "        OOO         ooooo                     OO             ooooo       OO" <<endl;
        gotoxy(5+i, 18);
        cout << "        OO      ooo      ooo                  OO          ooo     ooo   OO" <<endl;
        gotoxy(5+i, 19);
        cout << "        OOOOOOoooo OOOOOOO ooooOOOOOOOOOOOOOOOOOOOOOOOOoooo OOOOOO oooo" <<endl;
        gotoxy(5+i, 20);
        cout << "               oo ooo   ooo oo                           oo ooo  ooo oo" <<endl;
        gotoxy(5+i, 21);
        cout << "               ooo ooooo ooo                             ooo oooooo oo" <<endl;
        gotoxy(5+i, 22);
        cout << "                 ooo    ooo                               ooo     ooo" <<endl;
        gotoxy(5+i, 23);
        cout << "                     ooo                                      ooo" <<endl <<endl <<endl;

    }
    setColor(WHITE);
}

void imagen_restauracion(){
    setColor(LIGHTCYAN);
    gotoxy(3,24);
    cout << "_____________   _____________   _____________   _____________   _____________   _____________   " <<endl;
    gotoxy(3,25);
    cout << "_________   _____________   _____________   _____________   _____________   _____________   ____" <<endl;
    setColor(LIGHTMAGENTA);
    for (int i=0; i<25; i++){
        gotoxy(3+i, 5);
        cout << "       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 6);
        cout << "      OO        OO        OO        OO       OO" <<endl;
        gotoxy(5+i, 7);
        cout << "       OOO     OOOO       OOOO      OOOO       OO" <<endl;
        gotoxy(5+i, 8);
        cout << "        OOOOOOOO   OOOOOOOO  OOOOOOOO   OOOOOOOO" <<endl;
        gotoxy(5+i, 9);
        cout << "        OOO                                   OO" <<endl;
        gotoxy(5+i, 10);
        cout << "        OOO    OOOOOOOOOOOOOOOOOOOOOOOOO     OOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 11);
        cout << "        OOO   OOO                      OO    OO           OOO" <<endl;
        gotoxy(5+i, 12);
        cout << "        OOO   OOO     RESTAURANDO      OO    OO             OO" <<endl;
        gotoxy(5+i, 13);
        cout << "        OOO   OOO                      OO    OO              OOO" <<endl;
        gotoxy(5+i, 14);
        cout << "        OOO   OOO                      OO    OOOOOOOOOOOOOOOOOOOOOOO" <<endl;
        gotoxy(5+i, 15);
        cout << "        OOO   OOOOOOOOOOOOOOOOOOOOOOOOOOOO    OO                    OOOO" <<endl;
        gotoxy(5+i, 16);
        cout << "        OOO                                   OO                     OOOO" <<endl;
        gotoxy(5+i, 17);
        cout << "        OOO         ooooo                     OO             ooooo       OO" <<endl;
        gotoxy(5+i, 18);
        cout << "        OO      ooo      ooo                  OO          ooo     ooo   OO" <<endl;
        gotoxy(5+i, 19);
        cout << "        OOOOOOoooo OOOOOOO ooooOOOOOOOOOOOOOOOOOOOOOOOOoooo OOOOOO oooo" <<endl;
        gotoxy(5+i, 20);
        cout << "               oo ooo   ooo oo                           oo ooo  ooo oo" <<endl;
        gotoxy(5+i, 21);
        cout << "               ooo ooooo ooo                             ooo oooooo oo" <<endl;
        gotoxy(5+i, 22);
        cout << "                 ooo    ooo                               ooo     ooo" <<endl;
        gotoxy(5+i, 23);
        cout << "                     ooo                                      ooo" <<endl <<endl <<endl;

    }
    setColor(WHITE);
}
